//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.26 at 10:41:00 PM IST 
//


package com.GS.BlueDart.stub2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ALTInstructionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ALTInstructionRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AWBNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AltInstRequestType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ConsigneeNewAddress" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.ALTInstructionUpdate}ConsigneeNewAddress" minOccurs="0"/&gt;
 *         &lt;element name="LandMark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MobileNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreferDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PreferTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TimeSlot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ALTInstructionRequest", propOrder = {
    "awbNo",
    "altInstRequestType",
    "consigneeNewAddress",
    "landMark",
    "mobileNo",
    "preferDate",
    "preferTime",
    "timeSlot"
})
public class ALTInstructionRequest {

    @XmlElement(name = "AWBNo", nillable = true)
    protected String awbNo;
    @XmlElement(name = "AltInstRequestType", nillable = true)
    protected String altInstRequestType;
    @XmlElement(name = "ConsigneeNewAddress", nillable = true)
    protected ConsigneeNewAddress consigneeNewAddress;
    @XmlElement(name = "LandMark", nillable = true)
    protected String landMark;
    @XmlElement(name = "MobileNo", nillable = true)
    protected String mobileNo;
    @XmlElement(name = "PreferDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar preferDate;
    @XmlElement(name = "PreferTime", nillable = true)
    protected String preferTime;
    @XmlElement(name = "TimeSlot", nillable = true)
    protected String timeSlot;

    /**
     * Gets the value of the awbNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAWBNo() {
        return awbNo;
    }

    /**
     * Sets the value of the awbNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAWBNo(String value) {
        this.awbNo = value;
    }

    /**
     * Gets the value of the altInstRequestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltInstRequestType() {
        return altInstRequestType;
    }

    /**
     * Sets the value of the altInstRequestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltInstRequestType(String value) {
        this.altInstRequestType = value;
    }

    /**
     * Gets the value of the consigneeNewAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ConsigneeNewAddress }
     *     
     */
    public ConsigneeNewAddress getConsigneeNewAddress() {
        return consigneeNewAddress;
    }

    /**
     * Sets the value of the consigneeNewAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsigneeNewAddress }
     *     
     */
    public void setConsigneeNewAddress(ConsigneeNewAddress value) {
        this.consigneeNewAddress = value;
    }

    /**
     * Gets the value of the landMark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLandMark() {
        return landMark;
    }

    /**
     * Sets the value of the landMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLandMark(String value) {
        this.landMark = value;
    }

    /**
     * Gets the value of the mobileNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * Sets the value of the mobileNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileNo(String value) {
        this.mobileNo = value;
    }

    /**
     * Gets the value of the preferDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPreferDate() {
        return preferDate;
    }

    /**
     * Sets the value of the preferDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPreferDate(XMLGregorianCalendar value) {
        this.preferDate = value;
    }

    /**
     * Gets the value of the preferTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferTime() {
        return preferTime;
    }

    /**
     * Sets the value of the preferTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferTime(String value) {
        this.preferTime = value;
    }

    /**
     * Gets the value of the timeSlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeSlot() {
        return timeSlot;
    }

    /**
     * Sets the value of the timeSlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeSlot(String value) {
        this.timeSlot = value;
    }

}
