//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.26 at 10:41:00 PM IST 
//


package com.GS.BlueDart.stub2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CustALTInstructionUpdateResult" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.ALTInstructionUpdate}ALTInstructionResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "custALTInstructionUpdateResult"
})
@XmlRootElement(name = "CustALTInstructionUpdateResponse", namespace = "http://tempuri.org/")
public class CustALTInstructionUpdateResponse {

    @XmlElement(name = "CustALTInstructionUpdateResult", namespace = "http://tempuri.org/", nillable = true)
    protected ALTInstructionResponse custALTInstructionUpdateResult;

    /**
     * Gets the value of the custALTInstructionUpdateResult property.
     * 
     * @return
     *     possible object is
     *     {@link ALTInstructionResponse }
     *     
     */
    public ALTInstructionResponse getCustALTInstructionUpdateResult() {
        return custALTInstructionUpdateResult;
    }

    /**
     * Sets the value of the custALTInstructionUpdateResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ALTInstructionResponse }
     *     
     */
    public void setCustALTInstructionUpdateResult(ALTInstructionResponse value) {
        this.custALTInstructionUpdateResult = value;
    }

}
