//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommodityDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommodityDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CommodityDetail1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommodityDetail2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommodityDetail3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommodityDetail", propOrder = {
    "commodityDetail1",
    "commodityDetail2",
    "commodityDetail3"
})
public class CommodityDetail {

    @XmlElement(name = "CommodityDetail1", nillable = true)
    protected String commodityDetail1;
    @XmlElement(name = "CommodityDetail2", nillable = true)
    protected String commodityDetail2;
    @XmlElement(name = "CommodityDetail3", nillable = true)
    protected String commodityDetail3;

    /**
     * Gets the value of the commodityDetail1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityDetail1() {
        return commodityDetail1;
    }

    /**
     * Sets the value of the commodityDetail1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityDetail1(String value) {
        this.commodityDetail1 = value;
    }

    /**
     * Gets the value of the commodityDetail2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityDetail2() {
        return commodityDetail2;
    }

    /**
     * Sets the value of the commodityDetail2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityDetail2(String value) {
        this.commodityDetail2 = value;
    }

    /**
     * Gets the value of the commodityDetail3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityDetail3() {
        return commodityDetail3;
    }

    /**
     * Sets the value of the commodityDetail3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityDetail3(String value) {
        this.commodityDetail3 = value;
    }

}
