//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.GrowSimplee.BlueDart.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WayBillGenerationRequest_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "WayBillGenerationRequest");
    private final static QName _Consignee_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "Consignee");
    private final static QName _ReturnAddress_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ReturnAddress");
    private final static QName _Services_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "Services");
    private final static QName _CommodityDetail_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "CommodityDetail");
    private final static QName _ArrayOfDimension_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ArrayOfDimension");
    private final static QName _Dimension_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "Dimension");
    private final static QName _ArrayOfDynamicQCDetails_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ArrayOfDynamicQCDetails");
    private final static QName _DynamicQCDetails_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "DynamicQCDetails");
    private final static QName _ArrayOfItemImage_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ArrayOfItemImage");
    private final static QName _ItemImage_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ItemImage");
    private final static QName _ArrayOfItemDetails_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ArrayOfItemDetails");
    private final static QName _ItemDetails_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ItemDetails");
    private final static QName _Shipper_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "Shipper");
    private final static QName _WayBillGenerationResponse_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "WayBillGenerationResponse");
    private final static QName _ArrayOfWayBillGenerationStatus_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ArrayOfWayBillGenerationStatus");
    private final static QName _WayBillGenerationStatus_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "WayBillGenerationStatus");
    private final static QName _ArrayOfWayBillGenerationRequest_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ArrayOfWayBillGenerationRequest");
    private final static QName _ArrayOfWayBillGenerationResponse_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "ArrayOfWayBillGenerationResponse");
    private final static QName _AWBCancelationRequest_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "AWBCancelationRequest");
    private final static QName _AWBCancelationResponse_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "AWBCancelationResponse");
    private final static QName _EwayBillRequest_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "EwayBillRequest");
    private final static QName _EwayBillResponse_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", "EwayBillResponse");
    private final static QName _OTPBasedDelivery_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration", "OTPBasedDelivery");
    private final static QName _PrinterLableSize_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration", "PrinterLableSize");
    private final static QName _ProductType_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration", "ProductType");
    private final static QName _UserProfile_QNAME = new QName("http://schemas.datacontract.org/2004/07/SAPI.Entities.Admin", "UserProfile");
    private final static QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private final static QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private final static QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private final static QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private final static QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private final static QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private final static QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private final static QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private final static QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private final static QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private final static QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private final static QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
    private final static QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private final static QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private final static QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private final static QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private final static QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private final static QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private final static QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private final static QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private final static QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.GrowSimplee.BlueDart.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenerateWayBill }
     * 
     */
    public GenerateWayBill createGenerateWayBill() {
        return new GenerateWayBill();
    }

    /**
     * Create an instance of {@link WayBillGenerationRequest }
     * 
     */
    public WayBillGenerationRequest createWayBillGenerationRequest() {
        return new WayBillGenerationRequest();
    }

    /**
     * Create an instance of {@link UserProfile }
     * 
     */
    public UserProfile createUserProfile() {
        return new UserProfile();
    }

    /**
     * Create an instance of {@link GenerateWayBillResponse }
     * 
     */
    public GenerateWayBillResponse createGenerateWayBillResponse() {
        return new GenerateWayBillResponse();
    }

    /**
     * Create an instance of {@link WayBillGenerationResponse }
     * 
     */
    public WayBillGenerationResponse createWayBillGenerationResponse() {
        return new WayBillGenerationResponse();
    }

    /**
     * Create an instance of {@link ImportData }
     * 
     */
    public ImportData createImportData() {
        return new ImportData();
    }

    /**
     * Create an instance of {@link ArrayOfWayBillGenerationRequest }
     * 
     */
    public ArrayOfWayBillGenerationRequest createArrayOfWayBillGenerationRequest() {
        return new ArrayOfWayBillGenerationRequest();
    }

    /**
     * Create an instance of {@link ImportDataResponse }
     * 
     */
    public ImportDataResponse createImportDataResponse() {
        return new ImportDataResponse();
    }

    /**
     * Create an instance of {@link ArrayOfWayBillGenerationResponse }
     * 
     */
    public ArrayOfWayBillGenerationResponse createArrayOfWayBillGenerationResponse() {
        return new ArrayOfWayBillGenerationResponse();
    }

    /**
     * Create an instance of {@link CancelWaybill }
     * 
     */
    public CancelWaybill createCancelWaybill() {
        return new CancelWaybill();
    }

    /**
     * Create an instance of {@link AWBCancelationRequest }
     * 
     */
    public AWBCancelationRequest createAWBCancelationRequest() {
        return new AWBCancelationRequest();
    }

    /**
     * Create an instance of {@link CancelWaybillResponse }
     * 
     */
    public CancelWaybillResponse createCancelWaybillResponse() {
        return new CancelWaybillResponse();
    }

    /**
     * Create an instance of {@link AWBCancelationResponse }
     * 
     */
    public AWBCancelationResponse createAWBCancelationResponse() {
        return new AWBCancelationResponse();
    }

    /**
     * Create an instance of {@link UpdateEwayBill }
     * 
     */
    public UpdateEwayBill createUpdateEwayBill() {
        return new UpdateEwayBill();
    }

    /**
     * Create an instance of {@link EwayBillRequest }
     * 
     */
    public EwayBillRequest createEwayBillRequest() {
        return new EwayBillRequest();
    }

    /**
     * Create an instance of {@link UpdateEwayBillResponse }
     * 
     */
    public UpdateEwayBillResponse createUpdateEwayBillResponse() {
        return new UpdateEwayBillResponse();
    }

    /**
     * Create an instance of {@link EwayBillResponse }
     * 
     */
    public EwayBillResponse createEwayBillResponse() {
        return new EwayBillResponse();
    }

    /**
     * Create an instance of {@link Consignee }
     * 
     */
    public Consignee createConsignee() {
        return new Consignee();
    }

    /**
     * Create an instance of {@link ReturnAddress }
     * 
     */
    public ReturnAddress createReturnAddress() {
        return new ReturnAddress();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link CommodityDetail }
     * 
     */
    public CommodityDetail createCommodityDetail() {
        return new CommodityDetail();
    }

    /**
     * Create an instance of {@link ArrayOfDimension }
     * 
     */
    public ArrayOfDimension createArrayOfDimension() {
        return new ArrayOfDimension();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link ArrayOfDynamicQCDetails }
     * 
     */
    public ArrayOfDynamicQCDetails createArrayOfDynamicQCDetails() {
        return new ArrayOfDynamicQCDetails();
    }

    /**
     * Create an instance of {@link DynamicQCDetails }
     * 
     */
    public DynamicQCDetails createDynamicQCDetails() {
        return new DynamicQCDetails();
    }

    /**
     * Create an instance of {@link ArrayOfItemImage }
     * 
     */
    public ArrayOfItemImage createArrayOfItemImage() {
        return new ArrayOfItemImage();
    }

    /**
     * Create an instance of {@link ItemImage }
     * 
     */
    public ItemImage createItemImage() {
        return new ItemImage();
    }

    /**
     * Create an instance of {@link ArrayOfItemDetails }
     * 
     */
    public ArrayOfItemDetails createArrayOfItemDetails() {
        return new ArrayOfItemDetails();
    }

    /**
     * Create an instance of {@link ItemDetails }
     * 
     */
    public ItemDetails createItemDetails() {
        return new ItemDetails();
    }

    /**
     * Create an instance of {@link Shipper }
     * 
     */
    public Shipper createShipper() {
        return new Shipper();
    }

    /**
     * Create an instance of {@link ArrayOfWayBillGenerationStatus }
     * 
     */
    public ArrayOfWayBillGenerationStatus createArrayOfWayBillGenerationStatus() {
        return new ArrayOfWayBillGenerationStatus();
    }

    /**
     * Create an instance of {@link WayBillGenerationStatus }
     * 
     */
    public WayBillGenerationStatus createWayBillGenerationStatus() {
        return new WayBillGenerationStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WayBillGenerationRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WayBillGenerationRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "WayBillGenerationRequest")
    public JAXBElement<WayBillGenerationRequest> createWayBillGenerationRequest(WayBillGenerationRequest value) {
        return new JAXBElement<WayBillGenerationRequest>(_WayBillGenerationRequest_QNAME, WayBillGenerationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Consignee }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Consignee }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "Consignee")
    public JAXBElement<Consignee> createConsignee(Consignee value) {
        return new JAXBElement<Consignee>(_Consignee_QNAME, Consignee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnAddress }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReturnAddress }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ReturnAddress")
    public JAXBElement<ReturnAddress> createReturnAddress(ReturnAddress value) {
        return new JAXBElement<ReturnAddress>(_ReturnAddress_QNAME, ReturnAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Services }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Services }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "Services")
    public JAXBElement<Services> createServices(Services value) {
        return new JAXBElement<Services>(_Services_QNAME, Services.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommodityDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CommodityDetail }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "CommodityDetail")
    public JAXBElement<CommodityDetail> createCommodityDetail(CommodityDetail value) {
        return new JAXBElement<CommodityDetail>(_CommodityDetail_QNAME, CommodityDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfDimension }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfDimension }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ArrayOfDimension")
    public JAXBElement<ArrayOfDimension> createArrayOfDimension(ArrayOfDimension value) {
        return new JAXBElement<ArrayOfDimension>(_ArrayOfDimension_QNAME, ArrayOfDimension.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dimension }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Dimension }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "Dimension")
    public JAXBElement<Dimension> createDimension(Dimension value) {
        return new JAXBElement<Dimension>(_Dimension_QNAME, Dimension.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfDynamicQCDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfDynamicQCDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ArrayOfDynamicQCDetails")
    public JAXBElement<ArrayOfDynamicQCDetails> createArrayOfDynamicQCDetails(ArrayOfDynamicQCDetails value) {
        return new JAXBElement<ArrayOfDynamicQCDetails>(_ArrayOfDynamicQCDetails_QNAME, ArrayOfDynamicQCDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DynamicQCDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DynamicQCDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "DynamicQCDetails")
    public JAXBElement<DynamicQCDetails> createDynamicQCDetails(DynamicQCDetails value) {
        return new JAXBElement<DynamicQCDetails>(_DynamicQCDetails_QNAME, DynamicQCDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfItemImage }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfItemImage }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ArrayOfItemImage")
    public JAXBElement<ArrayOfItemImage> createArrayOfItemImage(ArrayOfItemImage value) {
        return new JAXBElement<ArrayOfItemImage>(_ArrayOfItemImage_QNAME, ArrayOfItemImage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemImage }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ItemImage }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ItemImage")
    public JAXBElement<ItemImage> createItemImage(ItemImage value) {
        return new JAXBElement<ItemImage>(_ItemImage_QNAME, ItemImage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfItemDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfItemDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ArrayOfItemDetails")
    public JAXBElement<ArrayOfItemDetails> createArrayOfItemDetails(ArrayOfItemDetails value) {
        return new JAXBElement<ArrayOfItemDetails>(_ArrayOfItemDetails_QNAME, ArrayOfItemDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ItemDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ItemDetails")
    public JAXBElement<ItemDetails> createItemDetails(ItemDetails value) {
        return new JAXBElement<ItemDetails>(_ItemDetails_QNAME, ItemDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shipper }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Shipper }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "Shipper")
    public JAXBElement<Shipper> createShipper(Shipper value) {
        return new JAXBElement<Shipper>(_Shipper_QNAME, Shipper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WayBillGenerationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WayBillGenerationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "WayBillGenerationResponse")
    public JAXBElement<WayBillGenerationResponse> createWayBillGenerationResponse(WayBillGenerationResponse value) {
        return new JAXBElement<WayBillGenerationResponse>(_WayBillGenerationResponse_QNAME, WayBillGenerationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfWayBillGenerationStatus }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfWayBillGenerationStatus }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ArrayOfWayBillGenerationStatus")
    public JAXBElement<ArrayOfWayBillGenerationStatus> createArrayOfWayBillGenerationStatus(ArrayOfWayBillGenerationStatus value) {
        return new JAXBElement<ArrayOfWayBillGenerationStatus>(_ArrayOfWayBillGenerationStatus_QNAME, ArrayOfWayBillGenerationStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WayBillGenerationStatus }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WayBillGenerationStatus }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "WayBillGenerationStatus")
    public JAXBElement<WayBillGenerationStatus> createWayBillGenerationStatus(WayBillGenerationStatus value) {
        return new JAXBElement<WayBillGenerationStatus>(_WayBillGenerationStatus_QNAME, WayBillGenerationStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfWayBillGenerationRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfWayBillGenerationRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ArrayOfWayBillGenerationRequest")
    public JAXBElement<ArrayOfWayBillGenerationRequest> createArrayOfWayBillGenerationRequest(ArrayOfWayBillGenerationRequest value) {
        return new JAXBElement<ArrayOfWayBillGenerationRequest>(_ArrayOfWayBillGenerationRequest_QNAME, ArrayOfWayBillGenerationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfWayBillGenerationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfWayBillGenerationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "ArrayOfWayBillGenerationResponse")
    public JAXBElement<ArrayOfWayBillGenerationResponse> createArrayOfWayBillGenerationResponse(ArrayOfWayBillGenerationResponse value) {
        return new JAXBElement<ArrayOfWayBillGenerationResponse>(_ArrayOfWayBillGenerationResponse_QNAME, ArrayOfWayBillGenerationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AWBCancelationRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AWBCancelationRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "AWBCancelationRequest")
    public JAXBElement<AWBCancelationRequest> createAWBCancelationRequest(AWBCancelationRequest value) {
        return new JAXBElement<AWBCancelationRequest>(_AWBCancelationRequest_QNAME, AWBCancelationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AWBCancelationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AWBCancelationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "AWBCancelationResponse")
    public JAXBElement<AWBCancelationResponse> createAWBCancelationResponse(AWBCancelationResponse value) {
        return new JAXBElement<AWBCancelationResponse>(_AWBCancelationResponse_QNAME, AWBCancelationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EwayBillRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EwayBillRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "EwayBillRequest")
    public JAXBElement<EwayBillRequest> createEwayBillRequest(EwayBillRequest value) {
        return new JAXBElement<EwayBillRequest>(_EwayBillRequest_QNAME, EwayBillRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EwayBillResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EwayBillResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration", name = "EwayBillResponse")
    public JAXBElement<EwayBillResponse> createEwayBillResponse(EwayBillResponse value) {
        return new JAXBElement<EwayBillResponse>(_EwayBillResponse_QNAME, EwayBillResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OTPBasedDelivery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OTPBasedDelivery }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration", name = "OTPBasedDelivery")
    public JAXBElement<OTPBasedDelivery> createOTPBasedDelivery(OTPBasedDelivery value) {
        return new JAXBElement<OTPBasedDelivery>(_OTPBasedDelivery_QNAME, OTPBasedDelivery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrinterLableSize }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PrinterLableSize }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration", name = "PrinterLableSize")
    public JAXBElement<PrinterLableSize> createPrinterLableSize(PrinterLableSize value) {
        return new JAXBElement<PrinterLableSize>(_PrinterLableSize_QNAME, PrinterLableSize.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ProductType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration", name = "ProductType")
    public JAXBElement<ProductType> createProductType(ProductType value) {
        return new JAXBElement<ProductType>(_ProductType_QNAME, ProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserProfile }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UserProfile }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.Admin", name = "UserProfile")
    public JAXBElement<UserProfile> createUserProfile(UserProfile value) {
        return new JAXBElement<UserProfile>(_UserProfile_QNAME, UserProfile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QName }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

}
