//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTPBasedDelivery.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OTPBasedDelivery"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Default"/&gt;
 *     &lt;enumeration value="LastMileFixedOTPAutoGenerate"/&gt;
 *     &lt;enumeration value="LastMileFixedOTPpredefined"/&gt;
 *     &lt;enumeration value="LastMileDynamicOTP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OTPBasedDelivery", namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration")
@XmlEnum
public enum OTPBasedDelivery {

    @XmlEnumValue("Default")
    DEFAULT("Default"),
    @XmlEnumValue("LastMileFixedOTPAutoGenerate")
    LAST_MILE_FIXED_OTP_AUTO_GENERATE("LastMileFixedOTPAutoGenerate"),
    @XmlEnumValue("LastMileFixedOTPpredefined")
    LAST_MILE_FIXED_OT_PPREDEFINED("LastMileFixedOTPpredefined"),
    @XmlEnumValue("LastMileDynamicOTP")
    LAST_MILE_DYNAMIC_OTP("LastMileDynamicOTP");
    private final String value;

    OTPBasedDelivery(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OTPBasedDelivery fromValue(String v) {
        for (OTPBasedDelivery c: OTPBasedDelivery.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
