//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrinterLableSize.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrinterLableSize"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="LabelSizeA4S"/&gt;
 *     &lt;enumeration value="LabelSizeA4T"/&gt;
 *     &lt;enumeration value="LabelSize55X30"/&gt;
 *     &lt;enumeration value="LabelSize89X60"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PrinterLableSize", namespace = "http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration")
@XmlEnum
public enum PrinterLableSize {

    @XmlEnumValue("LabelSizeA4S")
    LABEL_SIZE_A_4_S("LabelSizeA4S"),
    @XmlEnumValue("LabelSizeA4T")
    LABEL_SIZE_A_4_T("LabelSizeA4T"),
    @XmlEnumValue("LabelSize55X30")
    LABEL_SIZE_55_X_30("LabelSize55X30"),
    @XmlEnumValue("LabelSize89X60")
    LABEL_SIZE_89_X_60("LabelSize89X60");
    private final String value;

    PrinterLableSize(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrinterLableSize fromValue(String v) {
        for (PrinterLableSize c: PrinterLableSize.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
