//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReturnAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReturnAddress"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ManifestNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnAddress3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnAddressinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnContact" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnEmailID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnLatitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnLongitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnMaskedContactNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnMobile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnPincode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnTelephone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnAddress", propOrder = {
    "manifestNumber",
    "returnAddress1",
    "returnAddress2",
    "returnAddress3",
    "returnAddressinfo",
    "returnContact",
    "returnEmailID",
    "returnLatitude",
    "returnLongitude",
    "returnMaskedContactNumber",
    "returnMobile",
    "returnPincode",
    "returnTelephone"
})
public class ReturnAddress {

    @XmlElement(name = "ManifestNumber", nillable = true)
    protected String manifestNumber;
    @XmlElement(name = "ReturnAddress1", nillable = true)
    protected String returnAddress1;
    @XmlElement(name = "ReturnAddress2", nillable = true)
    protected String returnAddress2;
    @XmlElement(name = "ReturnAddress3", nillable = true)
    protected String returnAddress3;
    @XmlElement(name = "ReturnAddressinfo", nillable = true)
    protected String returnAddressinfo;
    @XmlElement(name = "ReturnContact", nillable = true)
    protected String returnContact;
    @XmlElement(name = "ReturnEmailID", nillable = true)
    protected String returnEmailID;
    @XmlElement(name = "ReturnLatitude", nillable = true)
    protected String returnLatitude;
    @XmlElement(name = "ReturnLongitude", nillable = true)
    protected String returnLongitude;
    @XmlElement(name = "ReturnMaskedContactNumber", nillable = true)
    protected String returnMaskedContactNumber;
    @XmlElement(name = "ReturnMobile", nillable = true)
    protected String returnMobile;
    @XmlElement(name = "ReturnPincode", nillable = true)
    protected String returnPincode;
    @XmlElement(name = "ReturnTelephone", nillable = true)
    protected String returnTelephone;

    /**
     * Gets the value of the manifestNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManifestNumber() {
        return manifestNumber;
    }

    /**
     * Sets the value of the manifestNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManifestNumber(String value) {
        this.manifestNumber = value;
    }

    /**
     * Gets the value of the returnAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnAddress1() {
        return returnAddress1;
    }

    /**
     * Sets the value of the returnAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnAddress1(String value) {
        this.returnAddress1 = value;
    }

    /**
     * Gets the value of the returnAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnAddress2() {
        return returnAddress2;
    }

    /**
     * Sets the value of the returnAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnAddress2(String value) {
        this.returnAddress2 = value;
    }

    /**
     * Gets the value of the returnAddress3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnAddress3() {
        return returnAddress3;
    }

    /**
     * Sets the value of the returnAddress3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnAddress3(String value) {
        this.returnAddress3 = value;
    }

    /**
     * Gets the value of the returnAddressinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnAddressinfo() {
        return returnAddressinfo;
    }

    /**
     * Sets the value of the returnAddressinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnAddressinfo(String value) {
        this.returnAddressinfo = value;
    }

    /**
     * Gets the value of the returnContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnContact() {
        return returnContact;
    }

    /**
     * Sets the value of the returnContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnContact(String value) {
        this.returnContact = value;
    }

    /**
     * Gets the value of the returnEmailID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnEmailID() {
        return returnEmailID;
    }

    /**
     * Sets the value of the returnEmailID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnEmailID(String value) {
        this.returnEmailID = value;
    }

    /**
     * Gets the value of the returnLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnLatitude() {
        return returnLatitude;
    }

    /**
     * Sets the value of the returnLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnLatitude(String value) {
        this.returnLatitude = value;
    }

    /**
     * Gets the value of the returnLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnLongitude() {
        return returnLongitude;
    }

    /**
     * Sets the value of the returnLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnLongitude(String value) {
        this.returnLongitude = value;
    }

    /**
     * Gets the value of the returnMaskedContactNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnMaskedContactNumber() {
        return returnMaskedContactNumber;
    }

    /**
     * Sets the value of the returnMaskedContactNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnMaskedContactNumber(String value) {
        this.returnMaskedContactNumber = value;
    }

    /**
     * Gets the value of the returnMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnMobile() {
        return returnMobile;
    }

    /**
     * Sets the value of the returnMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnMobile(String value) {
        this.returnMobile = value;
    }

    /**
     * Gets the value of the returnPincode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnPincode() {
        return returnPincode;
    }

    /**
     * Sets the value of the returnPincode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnPincode(String value) {
        this.returnPincode = value;
    }

    /**
     * Gets the value of the returnTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnTelephone() {
        return returnTelephone;
    }

    /**
     * Sets the value of the returnTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnTelephone(String value) {
        this.returnTelephone = value;
    }

}
