//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Services complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Services"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AWBNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ActualWeight" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="AuthorizedDealerCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingReference1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingReference2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CollectableAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Commodity" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}CommodityDetail" minOccurs="0"/&gt;
 *         &lt;element name="CreditReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreditReferenceNo2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreditReferenceNo3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerEDD" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="DeclaredValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="DeferredDeliveryDays" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryTimeSlot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Dimensions" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}ArrayOfDimension" minOccurs="0"/&gt;
 *         &lt;element name="DynamicQCDetails" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}ArrayOfDynamicQCDetails" minOccurs="0"/&gt;
 *         &lt;element name="EsellerPlatformName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExchangeWaybillNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExportImportCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FavouringName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ForwardAWBNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ForwardLogisticCompName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IncotermCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InsuranceAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="InsurancePaidBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsChequeDD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsDedicatedDeliveryNetwork" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsEcomUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsForcePickup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsIntlEcomCSBUser" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsPartialPickup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsReversePickup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ItemCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="MarketplaceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MarketplaceURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OTPBasedDelivery" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration}OTPBasedDelivery" minOccurs="0"/&gt;
 *         &lt;element name="OTPCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Officecutofftime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OrderURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PDFOutputNotRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="PDFPrintContent" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="PackType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ParcelShopCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PayableAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PickupDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PickupMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PickupTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PickupType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PieceCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="PreferredDeliveryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PreferredPickupTimeSlot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PrinterLableSize" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration}PrinterLableSize" minOccurs="0"/&gt;
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProductFeature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProductType" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.AWBGeneration}ProductType" minOccurs="0"/&gt;
 *         &lt;element name="RegisterPickup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SpecialInstruction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SubProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SupplyOfIGST" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SupplyOfwoIGST" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TermsOfTrade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TotalCashPaytoCustomer" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Total_IGST_Paid" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="itemImg" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}ArrayOfItemImage" minOccurs="0"/&gt;
 *         &lt;element name="itemdtl" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}ArrayOfItemDetails" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Services", propOrder = {
    "awbNo",
    "actualWeight",
    "authorizedDealerCode",
    "billingReference1",
    "billingReference2",
    "collectableAmount",
    "commodity",
    "creditReferenceNo",
    "creditReferenceNo2",
    "creditReferenceNo3",
    "currencyCode",
    "customerEDD",
    "declaredValue",
    "deferredDeliveryDays",
    "deliveryTimeSlot",
    "dimensions",
    "dynamicQCDetails",
    "esellerPlatformName",
    "exchangeWaybillNo",
    "exportImportCode",
    "favouringName",
    "forwardAWBNo",
    "forwardLogisticCompName",
    "incotermCode",
    "insuranceAmount",
    "insurancePaidBy",
    "invoiceNo",
    "isChequeDD",
    "isDedicatedDeliveryNetwork",
    "isEcomUser",
    "isForcePickup",
    "isIntlEcomCSBUser",
    "isPartialPickup",
    "isReversePickup",
    "itemCount",
    "marketplaceName",
    "marketplaceURL",
    "otpBasedDelivery",
    "otpCode",
    "officecutofftime",
    "orderURL",
    "pdfOutputNotRequired",
    "pdfPrintContent",
    "packType",
    "parcelShopCode",
    "payableAt",
    "pickupDate",
    "pickupMode",
    "pickupTime",
    "pickupType",
    "pieceCount",
    "preferredDeliveryDate",
    "preferredPickupTimeSlot",
    "printerLableSize",
    "productCode",
    "productFeature",
    "productType",
    "registerPickup",
    "specialInstruction",
    "subProductCode",
    "supplyOfIGST",
    "supplyOfwoIGST",
    "termsOfTrade",
    "totalCashPaytoCustomer",
    "totalIGSTPaid",
    "itemImg",
    "itemdtl"
})
public class Services {

    @XmlElement(name = "AWBNo", nillable = true)
    protected String awbNo;
    @XmlElement(name = "ActualWeight")
    protected Double actualWeight;
    @XmlElement(name = "AuthorizedDealerCode", nillable = true)
    protected String authorizedDealerCode;
    @XmlElement(name = "BillingReference1", nillable = true)
    protected String billingReference1;
    @XmlElement(name = "BillingReference2", nillable = true)
    protected String billingReference2;
    @XmlElement(name = "CollectableAmount")
    protected Double collectableAmount;
    @XmlElement(name = "Commodity", nillable = true)
    protected CommodityDetail commodity;
    @XmlElement(name = "CreditReferenceNo", nillable = true)
    protected String creditReferenceNo;
    @XmlElement(name = "CreditReferenceNo2", nillable = true)
    protected String creditReferenceNo2;
    @XmlElement(name = "CreditReferenceNo3", nillable = true)
    protected String creditReferenceNo3;
    @XmlElement(name = "CurrencyCode", nillable = true)
    protected String currencyCode;
    @XmlElement(name = "CustomerEDD")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar customerEDD;
    @XmlElement(name = "DeclaredValue")
    protected Double declaredValue;
    @XmlElement(name = "DeferredDeliveryDays")
    protected Integer deferredDeliveryDays;
    @XmlElement(name = "DeliveryTimeSlot", nillable = true)
    protected String deliveryTimeSlot;
    @XmlElement(name = "Dimensions", nillable = true)
    protected ArrayOfDimension dimensions;
    @XmlElement(name = "DynamicQCDetails", nillable = true)
    protected ArrayOfDynamicQCDetails dynamicQCDetails;
    @XmlElement(name = "EsellerPlatformName", nillable = true)
    protected String esellerPlatformName;
    @XmlElement(name = "ExchangeWaybillNo", nillable = true)
    protected String exchangeWaybillNo;
    @XmlElement(name = "ExportImportCode", nillable = true)
    protected String exportImportCode;
    @XmlElement(name = "FavouringName", nillable = true)
    protected String favouringName;
    @XmlElement(name = "ForwardAWBNo", nillable = true)
    protected String forwardAWBNo;
    @XmlElement(name = "ForwardLogisticCompName", nillable = true)
    protected String forwardLogisticCompName;
    @XmlElement(name = "IncotermCode", nillable = true)
    protected String incotermCode;
    @XmlElement(name = "InsuranceAmount")
    protected Double insuranceAmount;
    @XmlElement(name = "InsurancePaidBy", nillable = true)
    protected String insurancePaidBy;
    @XmlElement(name = "InvoiceNo", nillable = true)
    protected String invoiceNo;
    @XmlElement(name = "IsChequeDD", nillable = true)
    protected String isChequeDD;
    @XmlElement(name = "IsDedicatedDeliveryNetwork")
    protected Boolean isDedicatedDeliveryNetwork;
    @XmlElement(name = "IsEcomUser", nillable = true)
    protected String isEcomUser;
    @XmlElement(name = "IsForcePickup")
    protected Boolean isForcePickup;
    @XmlElement(name = "IsIntlEcomCSBUser")
    protected Boolean isIntlEcomCSBUser;
    @XmlElement(name = "IsPartialPickup")
    protected Boolean isPartialPickup;
    @XmlElement(name = "IsReversePickup")
    protected Boolean isReversePickup;
    @XmlElement(name = "ItemCount")
    protected Integer itemCount;
    @XmlElement(name = "MarketplaceName", nillable = true)
    protected String marketplaceName;
    @XmlElement(name = "MarketplaceURL", nillable = true)
    protected String marketplaceURL;
    @XmlElement(name = "OTPBasedDelivery")
    @XmlSchemaType(name = "string")
    protected OTPBasedDelivery otpBasedDelivery;
    @XmlElement(name = "OTPCode", nillable = true)
    protected String otpCode;
    @XmlElement(name = "Officecutofftime", nillable = true)
    protected String officecutofftime;
    @XmlElement(name = "OrderURL", nillable = true)
    protected String orderURL;
    @XmlElement(name = "PDFOutputNotRequired")
    protected Boolean pdfOutputNotRequired;
    @XmlElement(name = "PDFPrintContent", nillable = true)
    protected byte[] pdfPrintContent;
    @XmlElement(name = "PackType", nillable = true)
    protected String packType;
    @XmlElement(name = "ParcelShopCode", nillable = true)
    protected String parcelShopCode;
    @XmlElement(name = "PayableAt", nillable = true)
    protected String payableAt;
    @XmlElement(name = "PickupDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar pickupDate;
    @XmlElement(name = "PickupMode", nillable = true)
    protected String pickupMode;
    @XmlElement(name = "PickupTime", nillable = true)
    protected String pickupTime;
    @XmlElement(name = "PickupType", nillable = true)
    protected String pickupType;
    @XmlElement(name = "PieceCount")
    protected Integer pieceCount;
    @XmlElement(name = "PreferredDeliveryDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar preferredDeliveryDate;
    @XmlElement(name = "PreferredPickupTimeSlot", nillable = true)
    protected String preferredPickupTimeSlot;
    @XmlElement(name = "PrinterLableSize")
    @XmlSchemaType(name = "string")
    protected PrinterLableSize printerLableSize;
    @XmlElement(name = "ProductCode", nillable = true)
    protected String productCode;
    @XmlElement(name = "ProductFeature", nillable = true)
    protected String productFeature;
    @XmlElement(name = "ProductType")
    @XmlSchemaType(name = "string")
    protected ProductType productType;
    @XmlElement(name = "RegisterPickup")
    protected Boolean registerPickup;
    @XmlElement(name = "SpecialInstruction", nillable = true)
    protected String specialInstruction;
    @XmlElement(name = "SubProductCode", nillable = true)
    protected String subProductCode;
    @XmlElement(name = "SupplyOfIGST", nillable = true)
    protected String supplyOfIGST;
    @XmlElement(name = "SupplyOfwoIGST", nillable = true)
    protected String supplyOfwoIGST;
    @XmlElement(name = "TermsOfTrade", nillable = true)
    protected String termsOfTrade;
    @XmlElement(name = "TotalCashPaytoCustomer")
    protected Double totalCashPaytoCustomer;
    @XmlElement(name = "Total_IGST_Paid")
    protected Double totalIGSTPaid;
    @XmlElement(nillable = true)
    protected ArrayOfItemImage itemImg;
    @XmlElement(nillable = true)
    protected ArrayOfItemDetails itemdtl;

    /**
     * Gets the value of the awbNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAWBNo() {
        return awbNo;
    }

    /**
     * Sets the value of the awbNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAWBNo(String value) {
        this.awbNo = value;
    }

    /**
     * Gets the value of the actualWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getActualWeight() {
        return actualWeight;
    }

    /**
     * Sets the value of the actualWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setActualWeight(Double value) {
        this.actualWeight = value;
    }

    /**
     * Gets the value of the authorizedDealerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedDealerCode() {
        return authorizedDealerCode;
    }

    /**
     * Sets the value of the authorizedDealerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedDealerCode(String value) {
        this.authorizedDealerCode = value;
    }

    /**
     * Gets the value of the billingReference1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingReference1() {
        return billingReference1;
    }

    /**
     * Sets the value of the billingReference1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingReference1(String value) {
        this.billingReference1 = value;
    }

    /**
     * Gets the value of the billingReference2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingReference2() {
        return billingReference2;
    }

    /**
     * Sets the value of the billingReference2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingReference2(String value) {
        this.billingReference2 = value;
    }

    /**
     * Gets the value of the collectableAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCollectableAmount() {
        return collectableAmount;
    }

    /**
     * Sets the value of the collectableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCollectableAmount(Double value) {
        this.collectableAmount = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityDetail }
     *     
     */
    public CommodityDetail getCommodity() {
        return commodity;
    }

    /**
     * Sets the value of the commodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityDetail }
     *     
     */
    public void setCommodity(CommodityDetail value) {
        this.commodity = value;
    }

    /**
     * Gets the value of the creditReferenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditReferenceNo() {
        return creditReferenceNo;
    }

    /**
     * Sets the value of the creditReferenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditReferenceNo(String value) {
        this.creditReferenceNo = value;
    }

    /**
     * Gets the value of the creditReferenceNo2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditReferenceNo2() {
        return creditReferenceNo2;
    }

    /**
     * Sets the value of the creditReferenceNo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditReferenceNo2(String value) {
        this.creditReferenceNo2 = value;
    }

    /**
     * Gets the value of the creditReferenceNo3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditReferenceNo3() {
        return creditReferenceNo3;
    }

    /**
     * Sets the value of the creditReferenceNo3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditReferenceNo3(String value) {
        this.creditReferenceNo3 = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the customerEDD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCustomerEDD() {
        return customerEDD;
    }

    /**
     * Sets the value of the customerEDD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCustomerEDD(XMLGregorianCalendar value) {
        this.customerEDD = value;
    }

    /**
     * Gets the value of the declaredValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDeclaredValue() {
        return declaredValue;
    }

    /**
     * Sets the value of the declaredValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDeclaredValue(Double value) {
        this.declaredValue = value;
    }

    /**
     * Gets the value of the deferredDeliveryDays property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeferredDeliveryDays() {
        return deferredDeliveryDays;
    }

    /**
     * Sets the value of the deferredDeliveryDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeferredDeliveryDays(Integer value) {
        this.deferredDeliveryDays = value;
    }

    /**
     * Gets the value of the deliveryTimeSlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryTimeSlot() {
        return deliveryTimeSlot;
    }

    /**
     * Sets the value of the deliveryTimeSlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryTimeSlot(String value) {
        this.deliveryTimeSlot = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDimension }
     *     
     */
    public ArrayOfDimension getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDimension }
     *     
     */
    public void setDimensions(ArrayOfDimension value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the dynamicQCDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDynamicQCDetails }
     *     
     */
    public ArrayOfDynamicQCDetails getDynamicQCDetails() {
        return dynamicQCDetails;
    }

    /**
     * Sets the value of the dynamicQCDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDynamicQCDetails }
     *     
     */
    public void setDynamicQCDetails(ArrayOfDynamicQCDetails value) {
        this.dynamicQCDetails = value;
    }

    /**
     * Gets the value of the esellerPlatformName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsellerPlatformName() {
        return esellerPlatformName;
    }

    /**
     * Sets the value of the esellerPlatformName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsellerPlatformName(String value) {
        this.esellerPlatformName = value;
    }

    /**
     * Gets the value of the exchangeWaybillNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeWaybillNo() {
        return exchangeWaybillNo;
    }

    /**
     * Sets the value of the exchangeWaybillNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeWaybillNo(String value) {
        this.exchangeWaybillNo = value;
    }

    /**
     * Gets the value of the exportImportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportImportCode() {
        return exportImportCode;
    }

    /**
     * Sets the value of the exportImportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportImportCode(String value) {
        this.exportImportCode = value;
    }

    /**
     * Gets the value of the favouringName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavouringName() {
        return favouringName;
    }

    /**
     * Sets the value of the favouringName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavouringName(String value) {
        this.favouringName = value;
    }

    /**
     * Gets the value of the forwardAWBNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardAWBNo() {
        return forwardAWBNo;
    }

    /**
     * Sets the value of the forwardAWBNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardAWBNo(String value) {
        this.forwardAWBNo = value;
    }

    /**
     * Gets the value of the forwardLogisticCompName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardLogisticCompName() {
        return forwardLogisticCompName;
    }

    /**
     * Sets the value of the forwardLogisticCompName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardLogisticCompName(String value) {
        this.forwardLogisticCompName = value;
    }

    /**
     * Gets the value of the incotermCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncotermCode() {
        return incotermCode;
    }

    /**
     * Sets the value of the incotermCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncotermCode(String value) {
        this.incotermCode = value;
    }

    /**
     * Gets the value of the insuranceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInsuranceAmount() {
        return insuranceAmount;
    }

    /**
     * Sets the value of the insuranceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInsuranceAmount(Double value) {
        this.insuranceAmount = value;
    }

    /**
     * Gets the value of the insurancePaidBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsurancePaidBy() {
        return insurancePaidBy;
    }

    /**
     * Sets the value of the insurancePaidBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsurancePaidBy(String value) {
        this.insurancePaidBy = value;
    }

    /**
     * Gets the value of the invoiceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * Sets the value of the invoiceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNo(String value) {
        this.invoiceNo = value;
    }

    /**
     * Gets the value of the isChequeDD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsChequeDD() {
        return isChequeDD;
    }

    /**
     * Sets the value of the isChequeDD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsChequeDD(String value) {
        this.isChequeDD = value;
    }

    /**
     * Gets the value of the isDedicatedDeliveryNetwork property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDedicatedDeliveryNetwork() {
        return isDedicatedDeliveryNetwork;
    }

    /**
     * Sets the value of the isDedicatedDeliveryNetwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDedicatedDeliveryNetwork(Boolean value) {
        this.isDedicatedDeliveryNetwork = value;
    }

    /**
     * Gets the value of the isEcomUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEcomUser() {
        return isEcomUser;
    }

    /**
     * Sets the value of the isEcomUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEcomUser(String value) {
        this.isEcomUser = value;
    }

    /**
     * Gets the value of the isForcePickup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsForcePickup() {
        return isForcePickup;
    }

    /**
     * Sets the value of the isForcePickup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsForcePickup(Boolean value) {
        this.isForcePickup = value;
    }

    /**
     * Gets the value of the isIntlEcomCSBUser property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsIntlEcomCSBUser() {
        return isIntlEcomCSBUser;
    }

    /**
     * Sets the value of the isIntlEcomCSBUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsIntlEcomCSBUser(Boolean value) {
        this.isIntlEcomCSBUser = value;
    }

    /**
     * Gets the value of the isPartialPickup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPartialPickup() {
        return isPartialPickup;
    }

    /**
     * Sets the value of the isPartialPickup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPartialPickup(Boolean value) {
        this.isPartialPickup = value;
    }

    /**
     * Gets the value of the isReversePickup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsReversePickup() {
        return isReversePickup;
    }

    /**
     * Sets the value of the isReversePickup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReversePickup(Boolean value) {
        this.isReversePickup = value;
    }

    /**
     * Gets the value of the itemCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getItemCount() {
        return itemCount;
    }

    /**
     * Sets the value of the itemCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setItemCount(Integer value) {
        this.itemCount = value;
    }

    /**
     * Gets the value of the marketplaceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketplaceName() {
        return marketplaceName;
    }

    /**
     * Sets the value of the marketplaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketplaceName(String value) {
        this.marketplaceName = value;
    }

    /**
     * Gets the value of the marketplaceURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketplaceURL() {
        return marketplaceURL;
    }

    /**
     * Sets the value of the marketplaceURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketplaceURL(String value) {
        this.marketplaceURL = value;
    }

    /**
     * Gets the value of the otpBasedDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link OTPBasedDelivery }
     *     
     */
    public OTPBasedDelivery getOTPBasedDelivery() {
        return otpBasedDelivery;
    }

    /**
     * Sets the value of the otpBasedDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTPBasedDelivery }
     *     
     */
    public void setOTPBasedDelivery(OTPBasedDelivery value) {
        this.otpBasedDelivery = value;
    }

    /**
     * Gets the value of the otpCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTPCode() {
        return otpCode;
    }

    /**
     * Sets the value of the otpCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTPCode(String value) {
        this.otpCode = value;
    }

    /**
     * Gets the value of the officecutofftime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficecutofftime() {
        return officecutofftime;
    }

    /**
     * Sets the value of the officecutofftime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficecutofftime(String value) {
        this.officecutofftime = value;
    }

    /**
     * Gets the value of the orderURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderURL() {
        return orderURL;
    }

    /**
     * Sets the value of the orderURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderURL(String value) {
        this.orderURL = value;
    }

    /**
     * Gets the value of the pdfOutputNotRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPDFOutputNotRequired() {
        return pdfOutputNotRequired;
    }

    /**
     * Sets the value of the pdfOutputNotRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPDFOutputNotRequired(Boolean value) {
        this.pdfOutputNotRequired = value;
    }

    /**
     * Gets the value of the pdfPrintContent property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPDFPrintContent() {
        return pdfPrintContent;
    }

    /**
     * Sets the value of the pdfPrintContent property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPDFPrintContent(byte[] value) {
        this.pdfPrintContent = value;
    }

    /**
     * Gets the value of the packType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackType() {
        return packType;
    }

    /**
     * Sets the value of the packType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackType(String value) {
        this.packType = value;
    }

    /**
     * Gets the value of the parcelShopCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParcelShopCode() {
        return parcelShopCode;
    }

    /**
     * Sets the value of the parcelShopCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParcelShopCode(String value) {
        this.parcelShopCode = value;
    }

    /**
     * Gets the value of the payableAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayableAt() {
        return payableAt;
    }

    /**
     * Sets the value of the payableAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayableAt(String value) {
        this.payableAt = value;
    }

    /**
     * Gets the value of the pickupDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPickupDate() {
        return pickupDate;
    }

    /**
     * Sets the value of the pickupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPickupDate(XMLGregorianCalendar value) {
        this.pickupDate = value;
    }

    /**
     * Gets the value of the pickupMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupMode() {
        return pickupMode;
    }

    /**
     * Sets the value of the pickupMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupMode(String value) {
        this.pickupMode = value;
    }

    /**
     * Gets the value of the pickupTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupTime() {
        return pickupTime;
    }

    /**
     * Sets the value of the pickupTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupTime(String value) {
        this.pickupTime = value;
    }

    /**
     * Gets the value of the pickupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupType() {
        return pickupType;
    }

    /**
     * Sets the value of the pickupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupType(String value) {
        this.pickupType = value;
    }

    /**
     * Gets the value of the pieceCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPieceCount() {
        return pieceCount;
    }

    /**
     * Sets the value of the pieceCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPieceCount(Integer value) {
        this.pieceCount = value;
    }

    /**
     * Gets the value of the preferredDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPreferredDeliveryDate() {
        return preferredDeliveryDate;
    }

    /**
     * Sets the value of the preferredDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPreferredDeliveryDate(XMLGregorianCalendar value) {
        this.preferredDeliveryDate = value;
    }

    /**
     * Gets the value of the preferredPickupTimeSlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredPickupTimeSlot() {
        return preferredPickupTimeSlot;
    }

    /**
     * Sets the value of the preferredPickupTimeSlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredPickupTimeSlot(String value) {
        this.preferredPickupTimeSlot = value;
    }

    /**
     * Gets the value of the printerLableSize property.
     * 
     * @return
     *     possible object is
     *     {@link PrinterLableSize }
     *     
     */
    public PrinterLableSize getPrinterLableSize() {
        return printerLableSize;
    }

    /**
     * Sets the value of the printerLableSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrinterLableSize }
     *     
     */
    public void setPrinterLableSize(PrinterLableSize value) {
        this.printerLableSize = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the productFeature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductFeature() {
        return productFeature;
    }

    /**
     * Sets the value of the productFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductFeature(String value) {
        this.productFeature = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setProductType(ProductType value) {
        this.productType = value;
    }

    /**
     * Gets the value of the registerPickup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegisterPickup() {
        return registerPickup;
    }

    /**
     * Sets the value of the registerPickup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegisterPickup(Boolean value) {
        this.registerPickup = value;
    }

    /**
     * Gets the value of the specialInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialInstruction() {
        return specialInstruction;
    }

    /**
     * Sets the value of the specialInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialInstruction(String value) {
        this.specialInstruction = value;
    }

    /**
     * Gets the value of the subProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubProductCode() {
        return subProductCode;
    }

    /**
     * Sets the value of the subProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubProductCode(String value) {
        this.subProductCode = value;
    }

    /**
     * Gets the value of the supplyOfIGST property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplyOfIGST() {
        return supplyOfIGST;
    }

    /**
     * Sets the value of the supplyOfIGST property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplyOfIGST(String value) {
        this.supplyOfIGST = value;
    }

    /**
     * Gets the value of the supplyOfwoIGST property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplyOfwoIGST() {
        return supplyOfwoIGST;
    }

    /**
     * Sets the value of the supplyOfwoIGST property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplyOfwoIGST(String value) {
        this.supplyOfwoIGST = value;
    }

    /**
     * Gets the value of the termsOfTrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsOfTrade() {
        return termsOfTrade;
    }

    /**
     * Sets the value of the termsOfTrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsOfTrade(String value) {
        this.termsOfTrade = value;
    }

    /**
     * Gets the value of the totalCashPaytoCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalCashPaytoCustomer() {
        return totalCashPaytoCustomer;
    }

    /**
     * Sets the value of the totalCashPaytoCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalCashPaytoCustomer(Double value) {
        this.totalCashPaytoCustomer = value;
    }

    /**
     * Gets the value of the totalIGSTPaid property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalIGSTPaid() {
        return totalIGSTPaid;
    }

    /**
     * Sets the value of the totalIGSTPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalIGSTPaid(Double value) {
        this.totalIGSTPaid = value;
    }

    /**
     * Gets the value of the itemImg property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfItemImage }
     *     
     */
    public ArrayOfItemImage getItemImg() {
        return itemImg;
    }

    /**
     * Sets the value of the itemImg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemImage }
     *     
     */
    public void setItemImg(ArrayOfItemImage value) {
        this.itemImg = value;
    }

    /**
     * Gets the value of the itemdtl property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfItemDetails }
     *     
     */
    public ArrayOfItemDetails getItemdtl() {
        return itemdtl;
    }

    /**
     * Sets the value of the itemdtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemDetails }
     *     
     */
    public void setItemdtl(ArrayOfItemDetails value) {
        this.itemdtl = value;
    }

}
