//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Shipper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Shipper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CustomerAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerAddress3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerAddressinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerEmailID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerFiscalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerFiscalIDType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerGSTNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerLatitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerLongitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerMaskedContactNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerMobile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerPincode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerTelephone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsToPayCustomer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OriginArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Sender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Shipper", propOrder = {
    "customerAddress1",
    "customerAddress2",
    "customerAddress3",
    "customerAddressinfo",
    "customerCode",
    "customerEmailID",
    "customerFiscalID",
    "customerFiscalIDType",
    "customerGSTNumber",
    "customerLatitude",
    "customerLongitude",
    "customerMaskedContactNumber",
    "customerMobile",
    "customerName",
    "customerPincode",
    "customerTelephone",
    "isToPayCustomer",
    "originArea",
    "sender",
    "vendorCode"
})
public class Shipper {

    @XmlElement(name = "CustomerAddress1", nillable = true)
    protected String customerAddress1;
    @XmlElement(name = "CustomerAddress2", nillable = true)
    protected String customerAddress2;
    @XmlElement(name = "CustomerAddress3", nillable = true)
    protected String customerAddress3;
    @XmlElement(name = "CustomerAddressinfo", nillable = true)
    protected String customerAddressinfo;
    @XmlElement(name = "CustomerCode", nillable = true)
    protected String customerCode;
    @XmlElement(name = "CustomerEmailID", nillable = true)
    protected String customerEmailID;
    @XmlElement(name = "CustomerFiscalID", nillable = true)
    protected String customerFiscalID;
    @XmlElement(name = "CustomerFiscalIDType", nillable = true)
    protected String customerFiscalIDType;
    @XmlElement(name = "CustomerGSTNumber", nillable = true)
    protected String customerGSTNumber;
    @XmlElement(name = "CustomerLatitude", nillable = true)
    protected String customerLatitude;
    @XmlElement(name = "CustomerLongitude", nillable = true)
    protected String customerLongitude;
    @XmlElement(name = "CustomerMaskedContactNumber", nillable = true)
    protected String customerMaskedContactNumber;
    @XmlElement(name = "CustomerMobile", nillable = true)
    protected String customerMobile;
    @XmlElement(name = "CustomerName", nillable = true)
    protected String customerName;
    @XmlElement(name = "CustomerPincode", nillable = true)
    protected String customerPincode;
    @XmlElement(name = "CustomerTelephone", nillable = true)
    protected String customerTelephone;
    @XmlElement(name = "IsToPayCustomer")
    protected Boolean isToPayCustomer;
    @XmlElement(name = "OriginArea", nillable = true)
    protected String originArea;
    @XmlElement(name = "Sender", nillable = true)
    protected String sender;
    @XmlElement(name = "VendorCode", nillable = true)
    protected String vendorCode;

    /**
     * Gets the value of the customerAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress1() {
        return customerAddress1;
    }

    /**
     * Sets the value of the customerAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress1(String value) {
        this.customerAddress1 = value;
    }

    /**
     * Gets the value of the customerAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress2() {
        return customerAddress2;
    }

    /**
     * Sets the value of the customerAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress2(String value) {
        this.customerAddress2 = value;
    }

    /**
     * Gets the value of the customerAddress3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress3() {
        return customerAddress3;
    }

    /**
     * Sets the value of the customerAddress3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress3(String value) {
        this.customerAddress3 = value;
    }

    /**
     * Gets the value of the customerAddressinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddressinfo() {
        return customerAddressinfo;
    }

    /**
     * Sets the value of the customerAddressinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddressinfo(String value) {
        this.customerAddressinfo = value;
    }

    /**
     * Gets the value of the customerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Sets the value of the customerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCode(String value) {
        this.customerCode = value;
    }

    /**
     * Gets the value of the customerEmailID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmailID() {
        return customerEmailID;
    }

    /**
     * Sets the value of the customerEmailID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmailID(String value) {
        this.customerEmailID = value;
    }

    /**
     * Gets the value of the customerFiscalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerFiscalID() {
        return customerFiscalID;
    }

    /**
     * Sets the value of the customerFiscalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerFiscalID(String value) {
        this.customerFiscalID = value;
    }

    /**
     * Gets the value of the customerFiscalIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerFiscalIDType() {
        return customerFiscalIDType;
    }

    /**
     * Sets the value of the customerFiscalIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerFiscalIDType(String value) {
        this.customerFiscalIDType = value;
    }

    /**
     * Gets the value of the customerGSTNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerGSTNumber() {
        return customerGSTNumber;
    }

    /**
     * Sets the value of the customerGSTNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerGSTNumber(String value) {
        this.customerGSTNumber = value;
    }

    /**
     * Gets the value of the customerLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerLatitude() {
        return customerLatitude;
    }

    /**
     * Sets the value of the customerLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerLatitude(String value) {
        this.customerLatitude = value;
    }

    /**
     * Gets the value of the customerLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerLongitude() {
        return customerLongitude;
    }

    /**
     * Sets the value of the customerLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerLongitude(String value) {
        this.customerLongitude = value;
    }

    /**
     * Gets the value of the customerMaskedContactNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMaskedContactNumber() {
        return customerMaskedContactNumber;
    }

    /**
     * Sets the value of the customerMaskedContactNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMaskedContactNumber(String value) {
        this.customerMaskedContactNumber = value;
    }

    /**
     * Gets the value of the customerMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * Sets the value of the customerMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMobile(String value) {
        this.customerMobile = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerPincode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPincode() {
        return customerPincode;
    }

    /**
     * Sets the value of the customerPincode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPincode(String value) {
        this.customerPincode = value;
    }

    /**
     * Gets the value of the customerTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerTelephone() {
        return customerTelephone;
    }

    /**
     * Sets the value of the customerTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerTelephone(String value) {
        this.customerTelephone = value;
    }

    /**
     * Gets the value of the isToPayCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsToPayCustomer() {
        return isToPayCustomer;
    }

    /**
     * Sets the value of the isToPayCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsToPayCustomer(Boolean value) {
        this.isToPayCustomer = value;
    }

    /**
     * Gets the value of the originArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginArea() {
        return originArea;
    }

    /**
     * Sets the value of the originArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginArea(String value) {
        this.originArea = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSender(String value) {
        this.sender = value;
    }

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

}
