//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WayBillGenerationResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WayBillGenerationResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AWBNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AWBPrintContent" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="CCRCRDREF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DestinationArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DestinationLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsError" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsErrorInPU" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ShipmentPickupDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}ArrayOfWayBillGenerationStatus" minOccurs="0"/&gt;
 *         &lt;element name="TokenNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WayBillGenerationResponse", propOrder = {
    "awbNo",
    "awbPrintContent",
    "ccrcrdref",
    "destinationArea",
    "destinationLocation",
    "isError",
    "isErrorInPU",
    "shipmentPickupDate",
    "status",
    "tokenNumber"
})
public class WayBillGenerationResponse {

    @XmlElement(name = "AWBNo", nillable = true)
    protected String awbNo;
    @XmlElement(name = "AWBPrintContent", nillable = true)
    protected byte[] awbPrintContent;
    @XmlElement(name = "CCRCRDREF", nillable = true)
    protected String ccrcrdref;
    @XmlElement(name = "DestinationArea", nillable = true)
    protected String destinationArea;
    @XmlElement(name = "DestinationLocation", nillable = true)
    protected String destinationLocation;
    @XmlElement(name = "IsError")
    protected Boolean isError;
    @XmlElement(name = "IsErrorInPU")
    protected Boolean isErrorInPU;
    @XmlElement(name = "ShipmentPickupDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar shipmentPickupDate;
    @XmlElement(name = "Status", nillable = true)
    protected ArrayOfWayBillGenerationStatus status;
    @XmlElement(name = "TokenNumber", nillable = true)
    protected String tokenNumber;

    /**
     * Gets the value of the awbNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAWBNo() {
        return awbNo;
    }

    /**
     * Sets the value of the awbNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAWBNo(String value) {
        this.awbNo = value;
    }

    /**
     * Gets the value of the awbPrintContent property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getAWBPrintContent() {
        return awbPrintContent;
    }

    /**
     * Sets the value of the awbPrintContent property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setAWBPrintContent(byte[] value) {
        this.awbPrintContent = value;
    }

    /**
     * Gets the value of the ccrcrdref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCRCRDREF() {
        return ccrcrdref;
    }

    /**
     * Sets the value of the ccrcrdref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCRCRDREF(String value) {
        this.ccrcrdref = value;
    }

    /**
     * Gets the value of the destinationArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationArea() {
        return destinationArea;
    }

    /**
     * Sets the value of the destinationArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationArea(String value) {
        this.destinationArea = value;
    }

    /**
     * Gets the value of the destinationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationLocation() {
        return destinationLocation;
    }

    /**
     * Sets the value of the destinationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationLocation(String value) {
        this.destinationLocation = value;
    }

    /**
     * Gets the value of the isError property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsError() {
        return isError;
    }

    /**
     * Sets the value of the isError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsError(Boolean value) {
        this.isError = value;
    }

    /**
     * Gets the value of the isErrorInPU property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsErrorInPU() {
        return isErrorInPU;
    }

    /**
     * Sets the value of the isErrorInPU property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsErrorInPU(Boolean value) {
        this.isErrorInPU = value;
    }

    /**
     * Gets the value of the shipmentPickupDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShipmentPickupDate() {
        return shipmentPickupDate;
    }

    /**
     * Sets the value of the shipmentPickupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShipmentPickupDate(XMLGregorianCalendar value) {
        this.shipmentPickupDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfWayBillGenerationStatus }
     *     
     */
    public ArrayOfWayBillGenerationStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfWayBillGenerationStatus }
     *     
     */
    public void setStatus(ArrayOfWayBillGenerationStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the tokenNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenNumber() {
        return tokenNumber;
    }

    /**
     * Sets the value of the tokenNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenNumber(String value) {
        this.tokenNumber = value;
    }

}
