//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 05:52:48 PM IST 
//


package com.GS.BlueDart.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WayBillGenerationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WayBillGenerationRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Consignee" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}Consignee" minOccurs="0"/&gt;
 *         &lt;element name="Returnadds" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}ReturnAddress" minOccurs="0"/&gt;
 *         &lt;element name="Services" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}Services" minOccurs="0"/&gt;
 *         &lt;element name="Shipper" type="{http://schemas.datacontract.org/2004/07/SAPI.Entities.WayBillGeneration}Shipper" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WayBillGenerationRequest", propOrder = {
    "consignee",
    "returnadds",
    "services",
    "shipper"
})
public class WayBillGenerationRequest {

    @XmlElement(name = "Consignee", nillable = true)
    protected Consignee consignee;
    @XmlElement(name = "Returnadds", nillable = true)
    protected ReturnAddress returnadds;
    @XmlElement(name = "Services", nillable = true)
    protected Services services;
    @XmlElement(name = "Shipper", nillable = true)
    protected Shipper shipper;

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link Consignee }
     *     
     */
    public Consignee getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Consignee }
     *     
     */
    public void setConsignee(Consignee value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the returnadds property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnAddress }
     *     
     */
    public ReturnAddress getReturnadds() {
        return returnadds;
    }

    /**
     * Sets the value of the returnadds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnAddress }
     *     
     */
    public void setReturnadds(ReturnAddress value) {
        this.returnadds = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link Services }
     *     
     */
    public Services getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link Services }
     *     
     */
    public void setServices(Services value) {
        this.services = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return
     *     possible object is
     *     {@link Shipper }
     *     
     */
    public Shipper getShipper() {
        return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipper }
     *     
     */
    public void setShipper(Shipper value) {
        this.shipper = value;
    }

}
